### PR TITLE
Fix issues #97, #98, and #102

### PR DESCRIPTION
**Pull request by AlexanderSchultheiss**
See issues for further details.

### CODE REVIEW

**Review by pmbittner — APPROVED** [review]
Good catches and thank you for the fixes! :) Changes look good to me. For the fix of #97, the regex now has overlapping groups (match whole multiline comment, or match multiline comment begin). Are you sure that the first group always takes precedence over the second?

**Comment by AlexanderSchultheiss** [comment]
> Good catches and thank you for the fixes! :) Changes look good to me. For the fix of #97, the regex now has overlapping groups (match whole multiline comment, or match multiline comment begin). Are you sure that the first group always takes precedence over the second?

It worked in dozens of test runs that I did since I applied the change.

**Comment by AlexanderSchultheiss** [comment]
I found another edge case of #98 and adjusted the fix.

**Comment by AlexanderSchultheiss** [comment]
I converted the pull request back to a draft, because the current fixes are still insufficient.

**Comment by AlexanderSchultheiss** [comment]
These fixes are now addressed by pull request #103 .

**Pull request closed without merging**
